# Pretty cuts
#' @title Pretty Cuts
#'
#' @description Function removing set notation used by \code{\link[base]{cut}}
#'   or by \code{\link[Hmisc]{cut2}}.
#'
#' @details For a factor generated by \code{\link[Hmisc]{cut2}}
#'   \code{"[2057,2652)", "[2652,3092)", "..."}
#'   the function will return a character vector
#'   \code{"2057 - 2651", "2652 - 3091", "..." }
#'
#' @param cut_str A character or factor vector produced by \code{\link[base]{cut}}
#'   or by \code{\link[Hmisc]{cut2}} or a similar function. The set values have
#'   to be expressed as integer strings.
#'
#' @param only_cuts A logical, defults to \code{FALSE}. If \code{TRUE} the
#'   function will return only cut boundaries. For \code{FALSE} the function
#'   replaces each value with modified set value.
#'
#' @return A character vector.
#' @export
#'
#' @
#'
#' @examples
#' set.seed(123)
#' pretty_cuts(cut(x = runif(n = 1e3, min = 1, 1e4), breaks = 5))
#'
pretty_cuts <- function(cut_str, only_cuts = FALSE) {
    # Check if passed as factor and de-factorize if needed
    is.factor(cut_str) {
        cut_str <- as.character(cut_str)
    }

    # Check if passed vector is character vector and has the required
    # charactiertics
    checkmate::assert_character(
        x = cut_str,
        min.chars = 3,
        pattern = "*.\\d*.*\\d*",
        ignore.case = TRUE,
        fixed = FALSE,
        any.missing = TRUE,
        all.missing = FALSE,
        min.len = 1,
        unique = FALSE,
        null.ok = FALSE
    )
}
