# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Guess Vector Type
#'
#' @description Function analyses content of a factor vector and attempts to
#'   guess the correct type.
#'
#' @param x A vector of factor class.
#'
#' @return A scalar string with class name.
#'
#' @export
guess_vector_type <- function(x) {
    .Call(`_KEmisc_guess_vector_type`, x)
}

